"""Declarative base and reusable model mixins."""

from __future__ import annotations

import re
import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

from app.db.types import GUID

# Explicit, deterministic constraint names. Without these, Alembic cannot emit
# reliable `DROP CONSTRAINT` statements on SQLite, whose autogenerated names
# differ from PostgreSQL's.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

_CAMEL_TO_SNAKE = re.compile(r"(?<!^)(?=[A-Z])")


class Base(DeclarativeBase):
    """Root of the ORM hierarchy."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    # Fetch server-generated values (``server_default``, ``onupdate``) in the
    # same statement, via RETURNING.
    #
    # Without this, SQLAlchemy marks such columns expired after an INSERT or
    # UPDATE and reloads them on first access. Under asyncio that lazy reload
    # raises ``MissingGreenlet`` — so reading `updated_at` on a just-saved row
    # inside a response model would fail, and only on the write paths.
    __mapper_args__ = {"eager_defaults": True}

    @declared_attr.directive
    def __tablename__(cls) -> str:  # noqa: N805
        """Derive `snake_case` table names from `CamelCase` class names."""
        return _CAMEL_TO_SNAKE.sub("_", cls.__name__).lower()

    def __repr__(self) -> str:
        identifier = getattr(self, "id", None)
        return f"<{self.__class__.__name__} id={identifier}>"


class UUIDPrimaryKeyMixin:
    """UUID primary key.

    UUIDs are used instead of auto-increment integers so that identifiers can be
    generated client-side (the topology editor creates entities offline before
    they are persisted) and so that resource IDs do not leak row counts.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        GUID(), primary_key=True, default=uuid.uuid4, sort_order=-100
    )


class TimestampMixin:
    """`created_at` / `updated_at` maintained by the database."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, sort_order=100
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        sort_order=101,
    )
