"""initial schema

Revision ID: 22095d70a020
Revises:
Create Date: 2026-08-04 10:48:51.462884
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401  (rendered inside JSONB variants)
from sqlalchemy.dialects import postgresql  # noqa: F401  (JSONB variants)

# Autogenerated migrations reference custom column types by their full dotted
# path (e.g. `app.db.types.GUID()`), so the package must be importable here.
import app.db.types  # noqa: F401
from alembic import op

revision: str = "22095d70a020"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievements",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("icon", sa.String(length=80), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "progress",
                "mastery",
                "streak",
                "lab",
                "community",
                "special",
                name="achievementcategory",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "criteria",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("xp_reward", sa.Integer(), nullable=False),
        sa.Column("is_secret", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_achievements")),
    )
    with op.batch_alter_table("achievements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_achievements_slug"), ["slug"], unique=True)

    op.create_table(
        "tracks",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "level",
            sa.Enum(
                "foundation",
                "intermediate",
                "advanced",
                name="tracklevel",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("icon", sa.String(length=80), nullable=True),
        sa.Column("accent_color", sa.String(length=20), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracks")),
    )
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tracks_slug"), ["slug"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=True),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "student", "instructor", "admin", name="userrole", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tokens_valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "courses",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("track_id", app.db.types.GUID(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "difficulty",
            sa.Enum(
                "beginner",
                "intermediate",
                "advanced",
                "expert",
                name="difficulty",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("cover_image_url", sa.String(length=512), nullable=True),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "prerequisites",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("grants_certificate", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["track_id"], ["tracks.id"], name=op.f("fk_courses_track_id_tracks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
    )
    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_courses_slug"), ["slug"], unique=True)
        batch_op.create_index(batch_op.f("ix_courses_track_id"), ["track_id"], unique=False)
        batch_op.create_index("ix_courses_track_order", ["track_id", "order_index"], unique=False)

    op.create_table(
        "refresh_tokens",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("user_id", app.db.types.GUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", app.db.types.GUID(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", app.db.types.GUID(), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_replaced_by_id_refresh_tokens"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(
            "ix_refresh_tokens_user_family", ["user_id", "family_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_refresh_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "topologies",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("owner_id", app.db.types.GUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=512), nullable=True),
        sa.Column("is_template", sa.Boolean(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("device_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_topologies_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topologies")),
    )
    with op.batch_alter_table("topologies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_topologies_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(
            "ix_topologies_owner_updated", ["owner_id", "updated_at"], unique=False
        )

    op.create_table(
        "user_achievements",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("user_id", app.db.types.GUID(), nullable=False),
        sa.Column("achievement_id", app.db.types.GUID(), nullable=False),
        sa.Column(
            "earned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["achievements.id"],
            name=op.f("fk_user_achievements_achievement_id_achievements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_achievements_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_achievements")),
        sa.UniqueConstraint(
            "user_id", "achievement_id", name="uq_user_achievements_user_id_achievement_id"
        ),
    )
    with op.batch_alter_table("user_achievements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_achievements_achievement_id"), ["achievement_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_user_achievements_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_stats",
        sa.Column("user_id", app.db.types.GUID(), nullable=False),
        sa.Column("total_xp", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("lessons_completed", sa.Integer(), nullable=False),
        sa.Column("courses_completed", sa.Integer(), nullable=False),
        sa.Column("labs_completed", sa.Integer(), nullable=False),
        sa.Column("quizzes_passed", sa.Integer(), nullable=False),
        sa.Column("total_study_seconds", sa.Integer(), nullable=False),
        sa.Column("current_streak_days", sa.Integer(), nullable=False),
        sa.Column("longest_streak_days", sa.Integer(), nullable=False),
        sa.Column("last_activity_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_stats_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_stats")),
    )
    with op.batch_alter_table("user_stats", schema=None) as batch_op:
        batch_op.create_index("ix_user_stats_total_xp_desc", ["total_xp"], unique=False)

    op.create_table(
        "verification_tokens",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("user_id", app.db.types.GUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "email_verification",
                "password_reset",
                name="tokenpurpose",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_verification_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_tokens")),
    )
    with op.batch_alter_table("verification_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_verification_tokens_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_verification_tokens_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "xp_transactions",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("user_id", app.db.types.GUID(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "lesson_completed",
                "quiz_passed",
                "lab_completed",
                "course_completed",
                "achievement_earned",
                "streak_bonus",
                "manual_adjustment",
                name="xpreason",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reference_type", sa.String(length=40), nullable=True),
        sa.Column("reference_id", app.db.types.GUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_xp_transactions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_xp_transactions")),
    )
    with op.batch_alter_table("xp_transactions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_xp_transactions_user_created", ["user_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_xp_transactions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "certificates",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("user_id", app.db.types.GUID(), nullable=False),
        sa.Column("course_id", app.db.types.GUID(), nullable=False),
        sa.Column("serial", sa.String(length=40), nullable=False),
        sa.Column("verification_code", sa.String(length=64), nullable=False),
        sa.Column("recipient_name", sa.String(length=160), nullable=False),
        sa.Column("final_score", sa.Integer(), nullable=True),
        sa.Column("pdf_url", sa.String(length=512), nullable=True),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_certificates_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_certificates_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certificates")),
        sa.UniqueConstraint("user_id", "course_id", name="uq_certificates_user_id_course_id"),
    )
    with op.batch_alter_table("certificates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_certificates_course_id"), ["course_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_certificates_serial"), ["serial"], unique=True)
        batch_op.create_index(batch_op.f("ix_certificates_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_certificates_verification_code"), ["verification_code"], unique=True
        )

    op.create_table(
        "modules",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("course_id", app.db.types.GUID(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_modules_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modules")),
        sa.UniqueConstraint("course_id", "slug", name="uq_modules_course_id_slug"),
    )
    with op.batch_alter_table("modules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_modules_course_id"), ["course_id"], unique=False)
        batch_op.create_index("ix_modules_course_order", ["course_id", "order_index"], unique=False)

    op.create_table(
        "lessons",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("module_id", app.db.types.GUID(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=True),
        sa.Column(
            "lesson_type",
            sa.Enum(
                "theory",
                "interactive",
                "simulation",
                "lab",
                "quiz",
                "assessment",
                name="lessontype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "content_blocks",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "objectives",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("xp_reward", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["modules.id"],
            name=op.f("fk_lessons_module_id_modules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lessons")),
        sa.UniqueConstraint("module_id", "slug", name="uq_lessons_module_id_slug"),
    )
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lessons_module_id"), ["module_id"], unique=False)
        batch_op.create_index("ix_lessons_module_order", ["module_id", "order_index"], unique=False)

    op.create_table(
        "bookmarks",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("user_id", app.db.types.GUID(), nullable=False),
        sa.Column("lesson_id", app.db.types.GUID(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
            name=op.f("fk_bookmarks_lesson_id_lessons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_bookmarks_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookmarks")),
        sa.UniqueConstraint("user_id", "lesson_id", name="uq_bookmarks_user_id_lesson_id"),
    )
    with op.batch_alter_table("bookmarks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bookmarks_lesson_id"), ["lesson_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_bookmarks_user_id"), ["user_id"], unique=False)

    op.create_table(
        "enrollments",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("user_id", app.db.types.GUID(), nullable=False),
        sa.Column("course_id", app.db.types.GUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "completed",
                "paused",
                "dropped",
                name="enrollmentstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("progress_percent", sa.Float(), nullable=False),
        sa.Column("last_lesson_id", app.db.types.GUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_enrollments_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["last_lesson_id"],
            ["lessons.id"],
            name=op.f("fk_enrollments_last_lesson_id_lessons"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_enrollments_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrollments")),
        sa.UniqueConstraint("user_id", "course_id", name="uq_enrollments_user_id_course_id"),
    )
    with op.batch_alter_table("enrollments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_enrollments_course_id"), ["course_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_enrollments_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_enrollments_user_status", ["user_id", "status"], unique=False)

    op.create_table(
        "labs",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("lesson_id", app.db.types.GUID(), nullable=True),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "guided",
                "challenge",
                "troubleshooting",
                "design",
                name="labkind",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "scenario_type",
            sa.Enum(
                "home",
                "apartment",
                "small_office",
                "school",
                "university",
                "hospital",
                "bank",
                "enterprise",
                "isp",
                "campus",
                "cloud",
                "data_center",
                name="scenariotype",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column(
            "difficulty",
            sa.Enum(
                "beginner",
                "intermediate",
                "advanced",
                "expert",
                name="difficulty",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "requirements",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "objectives",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "initial_topology",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "grading_rules",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "fault_injections",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("time_limit_seconds", sa.Integer(), nullable=True),
        sa.Column("passing_score", sa.Integer(), nullable=False),
        sa.Column("xp_reward", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
            name=op.f("fk_labs_lesson_id_lessons"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_labs")),
    )
    with op.batch_alter_table("labs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_labs_lesson_id"), ["lesson_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_labs_scenario_type"), ["scenario_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_labs_slug"), ["slug"], unique=True)

    op.create_table(
        "lesson_progress",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("user_id", app.db.types.GUID(), nullable=False),
        sa.Column("lesson_id", app.db.types.GUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "not_started",
                "in_progress",
                "completed",
                name="progressstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("last_block_index", sa.Integer(), nullable=False),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
            name=op.f("fk_lesson_progress_lesson_id_lessons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_lesson_progress_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lesson_progress")),
        sa.UniqueConstraint("user_id", "lesson_id", name="uq_lesson_progress_user_id_lesson_id"),
    )
    with op.batch_alter_table("lesson_progress", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lesson_progress_lesson_id"), ["lesson_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_lesson_progress_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_lesson_progress_user_status", ["user_id", "status"], unique=False)

    op.create_table(
        "notes",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("user_id", app.db.types.GUID(), nullable=False),
        sa.Column("lesson_id", app.db.types.GUID(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("block_index", sa.Integer(), nullable=True),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
            name=op.f("fk_notes_lesson_id_lessons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
    )
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notes_lesson_id"), ["lesson_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_notes_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_notes_user_lesson", ["user_id", "lesson_id"], unique=False)

    op.create_table(
        "quizzes",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("lesson_id", app.db.types.GUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("passing_score", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=True),
        sa.Column("time_limit_seconds", sa.Integer(), nullable=True),
        sa.Column("shuffle_questions", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
            name=op.f("fk_quizzes_lesson_id_lessons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quizzes")),
        sa.UniqueConstraint("lesson_id", name=op.f("uq_quizzes_lesson_id")),
    )
    op.create_table(
        "lab_attempts",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("user_id", app.db.types.GUID(), nullable=False),
        sa.Column("lab_id", app.db.types.GUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "in_progress",
                "submitted",
                "passed",
                "failed",
                "abandoned",
                name="attemptstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "working_topology",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "check_results",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("score_percent", sa.Float(), nullable=True),
        sa.Column("hints_used", sa.Integer(), nullable=False),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lab_id"], ["labs.id"], name=op.f("fk_lab_attempts_lab_id_labs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_lab_attempts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lab_attempts")),
    )
    with op.batch_alter_table("lab_attempts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lab_attempts_lab_id"), ["lab_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_lab_attempts_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_lab_attempts_user_lab", ["user_id", "lab_id"], unique=False)

    op.create_table(
        "quiz_attempts",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("user_id", app.db.types.GUID(), nullable=False),
        sa.Column("quiz_id", app.db.types.GUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "in_progress",
                "submitted",
                "passed",
                "failed",
                "abandoned",
                name="attemptstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("score_percent", sa.Float(), nullable=True),
        sa.Column("points_earned", sa.Integer(), nullable=False),
        sa.Column("points_possible", sa.Integer(), nullable=False),
        sa.Column(
            "responses",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
            name=op.f("fk_quiz_attempts_quiz_id_quizzes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_quiz_attempts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_attempts")),
    )
    with op.batch_alter_table("quiz_attempts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_quiz_attempts_quiz_id"), ["quiz_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_quiz_attempts_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_quiz_attempts_user_quiz", ["user_id", "quiz_id"], unique=False)

    op.create_table(
        "quiz_questions",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("quiz_id", app.db.types.GUID(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "single_choice",
                "multiple_choice",
                "true_false",
                "fill_blank",
                "ordering",
                "matching",
                "subnet_calc",
                "cli_command",
                name="questiontype",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column(
            "answer_key",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("media_url", sa.String(length=512), nullable=True),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
            name=op.f("fk_quiz_questions_quiz_id_quizzes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_questions")),
    )
    with op.batch_alter_table("quiz_questions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_quiz_questions_quiz_id"), ["quiz_id"], unique=False)
        batch_op.create_index(
            "ix_quiz_questions_quiz_order", ["quiz_id", "order_index"], unique=False
        )

    op.create_table(
        "quiz_options",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("question_id", app.db.types.GUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["quiz_questions.id"],
            name=op.f("fk_quiz_options_question_id_quiz_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_options")),
    )
    with op.batch_alter_table("quiz_options", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quiz_options_question_id"), ["question_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quiz_options", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quiz_options_question_id"))

    op.drop_table("quiz_options")
    with op.batch_alter_table("quiz_questions", schema=None) as batch_op:
        batch_op.drop_index("ix_quiz_questions_quiz_order")
        batch_op.drop_index(batch_op.f("ix_quiz_questions_quiz_id"))

    op.drop_table("quiz_questions")
    with op.batch_alter_table("quiz_attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_quiz_attempts_user_quiz")
        batch_op.drop_index(batch_op.f("ix_quiz_attempts_user_id"))
        batch_op.drop_index(batch_op.f("ix_quiz_attempts_quiz_id"))

    op.drop_table("quiz_attempts")
    with op.batch_alter_table("lab_attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_lab_attempts_user_lab")
        batch_op.drop_index(batch_op.f("ix_lab_attempts_user_id"))
        batch_op.drop_index(batch_op.f("ix_lab_attempts_lab_id"))

    op.drop_table("lab_attempts")
    op.drop_table("quizzes")
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_index("ix_notes_user_lesson")
        batch_op.drop_index(batch_op.f("ix_notes_user_id"))
        batch_op.drop_index(batch_op.f("ix_notes_lesson_id"))

    op.drop_table("notes")
    with op.batch_alter_table("lesson_progress", schema=None) as batch_op:
        batch_op.drop_index("ix_lesson_progress_user_status")
        batch_op.drop_index(batch_op.f("ix_lesson_progress_user_id"))
        batch_op.drop_index(batch_op.f("ix_lesson_progress_lesson_id"))

    op.drop_table("lesson_progress")
    with op.batch_alter_table("labs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_labs_slug"))
        batch_op.drop_index(batch_op.f("ix_labs_scenario_type"))
        batch_op.drop_index(batch_op.f("ix_labs_lesson_id"))

    op.drop_table("labs")
    with op.batch_alter_table("enrollments", schema=None) as batch_op:
        batch_op.drop_index("ix_enrollments_user_status")
        batch_op.drop_index(batch_op.f("ix_enrollments_user_id"))
        batch_op.drop_index(batch_op.f("ix_enrollments_course_id"))

    op.drop_table("enrollments")
    with op.batch_alter_table("bookmarks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bookmarks_user_id"))
        batch_op.drop_index(batch_op.f("ix_bookmarks_lesson_id"))

    op.drop_table("bookmarks")
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.drop_index("ix_lessons_module_order")
        batch_op.drop_index(batch_op.f("ix_lessons_module_id"))

    op.drop_table("lessons")
    with op.batch_alter_table("modules", schema=None) as batch_op:
        batch_op.drop_index("ix_modules_course_order")
        batch_op.drop_index(batch_op.f("ix_modules_course_id"))

    op.drop_table("modules")
    with op.batch_alter_table("certificates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_certificates_verification_code"))
        batch_op.drop_index(batch_op.f("ix_certificates_user_id"))
        batch_op.drop_index(batch_op.f("ix_certificates_serial"))
        batch_op.drop_index(batch_op.f("ix_certificates_course_id"))

    op.drop_table("certificates")
    with op.batch_alter_table("xp_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_xp_transactions_user_id"))
        batch_op.drop_index("ix_xp_transactions_user_created")

    op.drop_table("xp_transactions")
    with op.batch_alter_table("verification_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_verification_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_verification_tokens_token_hash"))

    op.drop_table("verification_tokens")
    with op.batch_alter_table("user_stats", schema=None) as batch_op:
        batch_op.drop_index("ix_user_stats_total_xp_desc")

    op.drop_table("user_stats")
    with op.batch_alter_table("user_achievements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_achievements_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_achievements_achievement_id"))

    op.drop_table("user_achievements")
    with op.batch_alter_table("topologies", schema=None) as batch_op:
        batch_op.drop_index("ix_topologies_owner_updated")
        batch_op.drop_index(batch_op.f("ix_topologies_owner_id"))

    op.drop_table("topologies")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_user_id"))
        batch_op.drop_index("ix_refresh_tokens_user_family")
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_token_hash"))

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.drop_index("ix_courses_track_order")
        batch_op.drop_index(batch_op.f("ix_courses_track_id"))
        batch_op.drop_index(batch_op.f("ix_courses_slug"))

    op.drop_table("courses")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_role"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracks_slug"))

    op.drop_table("tracks")
    with op.batch_alter_table("achievements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_achievements_slug"))

    op.drop_table("achievements")
    # ### end Alembic commands ###
